trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - Services/Management/ManagementService/ManagementService/
    - Services/common/ci-steps-template.yml
    
pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- template: ../../../common/ci-vars-template.yml
  parameters:
      projectPath: Management/ManagementService/ManagementService
      projectName: ManagementService
      imageName: managementservice
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- template: ../../../common/ci-steps-template.yml
