version: '3.4'

services:
    identityservice:
        image: ${DOCKER_REGISTRY-}identityservice
        container_name: Identity
        build:
            context: .
            dockerfile: "../Identity/IdentityService/Dockerfile"

    apigateway:
        image: ${DOCKER_REGISTRY-}apigateway
        container_name: APIGateway
        build:
            context: .
            dockerfile: APIGateway/Dockerfile
        environment:
            IDENTITY_AUTHORITY: "identityservice"
        ports:
        - "80:80"
        links:
        - identityservice
        depends_on:
        - "identityservice"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: Rabbitmq

    cassandra:
        image: ${DOCKER_REGISTRY-}cassandrahourregistration
        container_name: HourRegistrationCassandraDB
        build:
            context: .
            dockerfile: "../HourRegistration/HourRegistrationAPI/Cassandra/Dockerfile"
        user: "cassandra"
        volumes: 
        - ../HourRegistration/HourRegistrationAPI/Cassandra/ :/usr/local/bin/

    hourregistrationapi:
        image: ${DOCKER_REGISTRY-}hourregistrationapi
        build:
            context: .
            dockerfile: "../HourRegistration/HourRegistrationAPI/HourRegistrationAPI/Dockerfile"
        depends_on: 
        - rabbitmq

    hourregistrationconsumer:
        image: ${DOCKER_REGISTRY-}hourregistrationconsumer
        build:
            context: .
            dockerfile: "../HourRegistration/HourRegistrationAPI/HourRegistrationConsumer/Dockerfile"
        depends_on: 
        - rabbitmq
        - cassandra

    management:
        image: ${DOCKER_REGISTRY-}management
        build:
            context: .
            dockerfile: "../Management/ManagementService/ManagementService/Dockerfile"
