version: '3.4'

services:
    apigateway:
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: APIGateway/Dockerfile
        container_name: APIGateway

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: Rabbitmq

    cassandra:
        image: ${DOCKER_REGISTRY-}cassandrahourregistration
        container_name: HourRegistrationCassandraDB
        build:
            context: .
            dockerfile: "../HourRegistration/HourRegistrationAPI/Cassandra/Dockerfile"
        user: "cassandra"
        volumes: 
        - ../HourRegistration/HourRegistrationAPI/Cassandra/ :/usr/local/bin/

    hourregistrationapi:
        image: ${DOCKER_REGISTRY-}hourregistrationapi
        build:
            context: .
            dockerfile: "../HourRegistration/HourRegistrationAPI/HourRegistrationAPI/Dockerfile"
        depends_on: 
        - rabbitmq


    hourregistrationconsumer:
        image: ${DOCKER_REGISTRY-}hourregistrationconsumer
        build:
            context: .
            dockerfile: "../HourRegistration/HourRegistrationAPI/HourRegistrationConsumer/Dockerfile"
        depends_on: 
        - rabbitmq
        - cassandra

    consul:
        image: consul:latest
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: consul

networks:
  default:
    external:
      name: hourregistrationnetwork

