version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: Rabbitmq

    cassandra:
        image: ${DOCKER_REGISTRY-}cassandrahourregistration
        container_name: HourRegistrationCassandraDB
        build:
            context: .
            dockerfile: "Cassandra/Dockerfile"
        user: "cassandra"
        volumes: 
        - ./Cassandra/ :/usr/local/bin/

    hourregistrationapi:
        image: ${DOCKER_REGISTRY-}hourregistrationapi
        build:
            context: .
            dockerfile: "HourRegistrationAPI/Dockerfile"
        ports:
        - "443:443"
        depends_on: 
        - rabbitmq


    hourregistrationconsumer:
        image: ${DOCKER_REGISTRY-}hourregistrationconsumer
        build:
            context: .
            dockerfile: "HourRegistrationConsumer/Dockerfile"
        depends_on: 
        - rabbitmq
        - cassandra

networks:
  default:
    external:
      name: hourregistrationnetwork
