version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine

    hourregistrationapi:
        image: ${DOCKER_REGISTRY-}hourregistrationapi
        build:
            context: .
            dockerfile: HourRegistrationAPI/Dockerfile
        ports:
        - "80:80"
        depends_on: 
        - rabbitmq


    hourregistrationconsumer:
        image: ${DOCKER_REGISTRY-}hourregistrationconsumer
        build:
            context: .
            dockerfile: "HourRegistrationConsumer/Dockerfile"
        depends_on: 
        - rabbitmq
