version: '3.4'

services:
  hourregistrationapi:
    image: ${DOCKER_REGISTRY-}hourregistrationapi
    build:
      context: .
      dockerfile: HourRegistrationAPI/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"