apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hourregistrationapi
  name: hourregistrationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hourregistrationapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: hourregistrationapi
    spec:
      containers:
      - image: hourregistrationapi
        imagePullPolicy: ""
        name: hourregistrationapi
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
