apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3-management
    name: rabbitmq
    ports:
    - containerPort: 15672
    - containerPort: 5672
    resources: {}
  restartPolicy: OnFailure
status: {}
